### ISSUE TITLE
A cross-reference to the step would be helpful.

### ISSUE THREAD

**Issue by jncd** [pivotal-cf/docs-altoros-heartbeat#5]
@antonsoroko and @ViktoriyaKotova 

On the installingcollectd.html page, it says "Remove the lines added at the *Downloading and Deploying the collectd add-on* stage." 
Could you clarify exactly what step of the procedure you are referring to? Is it step 9? I think it would be helpful to put in a link to exact step.

**Comment by antonsoroko** [comment]
@jncd 
Hi!
I believe it should be `step #1 of Creating a collectd Manifest section` instead of `Downloading and Deploying the collectd add-on stage`.

By the way, do you have technical documentation about how to write docs with your template?
For instance, I want to change [subnav](https://github.com/pivotal-cf/docs-altoros-heartbeat/blob/master/docs-book/master_middleman/source/subnavs/altoros-heartbeat_subnav.erb) but I don't know a proper way to do this.
It would be nice if you can share some tech docs with me. Thanks.

**Comment by jncd** [comment]
Hi,
Thanks for your PR for that fix.

I just added some help about the subnavs to the readme in the template. I
hope that answers your question.

See
https://github.com/pivotal-cf/docs-partners-template/blob/master/README.md#about-subnavs-of-published-tile-documentation

jane

**Comment by antonsoroko** [comment]
@jncd 
Hi! Thank for the info - good to know.
Maybe you can also provide some technical info about editing subnavs/documentation in general? E.g. which css styles/html tags should we use to create nesting in subnav. These kind of things.

**Comment by jncd** [comment]
Mostly, partner doc is short enough that nesting subnavs are not necessary.
(I don't want to encourage nesting by documenting it.)
If you have a good case where you think you want nested subnavs, add that
as a comment in your PR and ask the writer who merges the PR to nest the
subnavs if appropriate.
